server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  application:
    name: simple-blog

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kotlinblog
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:postgresql://localhost:5432/kotlinblog
    username: code09
    password: dkagh12#$
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
