### Health Check API 테스트
GET {{root-path}}/health


### 전체 Member 조회
GET {{root-path}}/members


### 전체 Post 조회
GET {{root-path}}/posts


### 특정 Member 조회
GET {{root-path}}/members/filter?filter=pr&count=2


### Member 등록
POST {{root-path}}/member
Content-Type: application/json

{
  "email": "email_test01@test.co.kr",
  "password": "password_6cb9b6655b6c",
  "role": "ADMIN"
}


### Member 조회
GET {{root-path}}/member/202


### Post 등록
POST {{root-path}}/post
Content-Type: application/json

{
  "title": "title00012",
  "content": "content00012",
  "memberId": 12
}